# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b0d0293e4b72fa63498fe6e79f5127badef739c66fb7fcfef207ab559f91a9168c268352bf12985a7fa2d3b247cffb6ddee448b9731ea93b6f3b221c66e80b

test:
  secret_key_base: dbe8509cbb6ae486d6d0907ec3fdc92c31b563b72d35350e2f65243cf52c3b0bab683b381f6aa86aab79af5ee994f2a137e550efb9140fd0d25f5d018da61a08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
